service: drm-mhs-contact-form
tenant: mflamb
app: davis-serverless-contact-form
plugins:
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs10.x
  profile: ${opt:profile, "drm-mhs"}
  region: ${opt:region, self:custom.secrets.REGION}
  stage: ${opt:stage, "dev"}
  environment:
    EMAIL: ${self:custom.secrets.EMAIL}
    SENDER: ${self:custom.secrets.SENDER}
    DOMAIN: ${self:custom.secrets.DOMAIN}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "ses:*"
      Resource: "*"

custom:
  secrets: ${file(secrets.${self:provider.stage}.json)}
  JCRLambdaName: ${self:service}-website-contact-form-${self:provider.stage}

  send:
    handler: emailDavis.send
    events:
      - http:
          path: email/send
          method: POST
          cors: true